# Generated by Django 3.2.9 on 2021-11-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
