# Generated by Django 3.2.9 on 2021-11-11 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
